name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - "1-particles"
          - "2-wator"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run tests
      run: sbt test

    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91

    # Add conditional steps based on the project path
    - name: Build and test project
      if: ${{ matrix.project == '1-particles' }}
      run: sbt test  # Replace with actual build/test command for 1-particles project

    - name: Build and test project
      if: ${{ matrix.project == '2-wator' }}
      run: sbt test  # Replace with actual build/test command for 2-wator project
